FROM quay.io/stephenwheet/ubi9-dev-image:latest

USER 10001

# Set default shell to zsh
ENV SHELL=/bin/zsh
ENV ZSH_DISABLE_COMPFIX=true
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8

# Create workspace dir used by VSCode
# RUN mkdir /opt/app-root/src/workspace/
