name: Build Multi-Arch Image on Release

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-runner-repo-rk1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        run: |
          docker run --rm --privileged alekitto/qemu-user-static --reset -p yes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Check secrets
        run: |
          echo ${{ secrets.GHCR_IMAGE_NAME }}
          echo ${{ secrets.GHCR_TOKEN }}
          
      - name: Build and Push Multi-Arch Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f ./fedora-dev-build/Dockerfile \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ secrets.GHCR_IMAGE_NAME }}:${{ github.event.release.tag_name }} \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ secrets.GHCR_IMAGE_NAME }}:latest \
            --push .
