name: Build Multi-Arch Image on Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: [self-hosted, dind]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Multi-Arch Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t <DOCKER_USERNAME>/<IMAGE_NAME>:${{ github.event.release.tag_name }} \
            -t <DOCKER_USERNAME>/<IMAGE_NAME>:latest \
            --push .